// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrcdZtz3fc-thm89YrtIyFKb9A27FPfd8',
    appId: '1:557976568066:web:57018f04bf12595fa2021b',
    messagingSenderId: '557976568066',
    projectId: 'finalfinal-5bebd',
    authDomain: 'finalfinal-5bebd.firebaseapp.com',
    storageBucket: 'finalfinal-5bebd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0adWglHx1aNUEjDYa164qcc8gGaKCbFs',
    appId: '1:557976568066:android:3e0905c88b8c9168a2021b',
    messagingSenderId: '557976568066',
    projectId: 'finalfinal-5bebd',
    storageBucket: 'finalfinal-5bebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZYZ_XJJ87nagGvaDMlg7p1Gm34AaWxk',
    appId: '1:557976568066:ios:cfb8376d085992cca2021b',
    messagingSenderId: '557976568066',
    projectId: 'finalfinal-5bebd',
    storageBucket: 'finalfinal-5bebd.appspot.com',
    iosClientId: '557976568066-kopg3c4amp5tlfeo0fi6t7uhm9tvb784.apps.googleusercontent.com',
    iosBundleId: 'com.example.finafinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAZYZ_XJJ87nagGvaDMlg7p1Gm34AaWxk',
    appId: '1:557976568066:ios:cfb8376d085992cca2021b',
    messagingSenderId: '557976568066',
    projectId: 'finalfinal-5bebd',
    storageBucket: 'finalfinal-5bebd.appspot.com',
    iosClientId: '557976568066-kopg3c4amp5tlfeo0fi6t7uhm9tvb784.apps.googleusercontent.com',
    iosBundleId: 'com.example.finafinalproject',
  );
}
